In [1]:
import time
import datetime
import numpy as np
import torch

from rl_firm.ppo_lstm_bounded import train, HyperParameters, RecurrentPPOAgent

## Some experiment to understand the squashing function

In [7]:
env = make_custom_env()()
obs, info = env.reset()

In [9]:
agent = RecurrentPPOAgent(obs_dim=int(np.array(env.observation_space.shape).prod()))
agent.eval()

lstm_state = (torch.zeros(agent.lstm.num_layers, 1, agent.lstm.hidden_size),
              torch.zeros(agent.lstm.num_layers, 1, agent.lstm.hidden_size))
done = torch.zeros(1)

In [11]:
hidden, cat_probs, cont_probs, lstm_state = agent._get_probs(torch.Tensor(np.array([obs])), lstm_state, done)

In [14]:
hidden.shape

torch.Size([1, 128])

In [16]:
u = cont_probs.rsample()
u.shape

torch.Size([1, 2])

In [18]:
y = torch.tanh(u)
y

tensor([[ 0.7872, -0.9597]], grad_fn=<TanhBackward0>)

In [19]:
a = agent._squash_affine(y)
a

tensor([[ 0.0157, -0.0182]], grad_fn=<AddBackward0>)

In [20]:
cont_probs.log_prob(u)

tensor([[-1.4839, -2.8043]], grad_fn=<SubBackward0>)

In [21]:
cont_probs.log_prob(u).sum(1)

tensor([-4.2883], grad_fn=<SumBackward1>)

In [22]:
cont_probs.log_prob(u).sum(-1)

tensor([-4.2883], grad_fn=<SumBackward1>)

## 2m anneal

In [ ]:
agent = train(HyperParameters(total_timesteps=2000000, anneal_lr=True), 'lstm_bounded_2m_anneal')
torch.save(agent.state_dict(), "./results/model/custom_lstm_bounded/2m_anneal.pt")

Training on device mps
Episode 1: Recent average episodic reward: 0.00, recent average episodic length: 1.00. Global step: 8
Episode 2: Recent average episodic reward: 0.06, recent average episodic length: 5.00. Global step: 72
Episode 3: Recent average episodic reward: 0.09, recent average episodic length: 7.67. Global step: 104
Episode 4: Recent average episodic reward: 0.10, recent average episodic length: 10.25. Global step: 144
Episode 5: Recent average episodic reward: 0.10, recent average episodic length: 12.00. Global step: 152
Episode 6: Recent average episodic reward: 0.09, recent average episodic length: 10.17. Global step: 160
Episode 7: Recent average episodic reward: 0.08, recent average episodic length: 11.71. Global step: 168
Episode 8: Recent average episodic reward: 0.07, recent average episodic length: 10.38. Global step: 184
Episode 9: Recent average episodic reward: 0.08, recent average episodic length: 12.11. Global step: 224
Episode 10: Recent average episodic re

## 4m anneal

In [ ]:
agent = train(HyperParameters(total_timesteps=4000000, anneal_lr=True), 'lstm_bounded_4m_anneal')
torch.save(agent.state_dict(), "./results/model/custom_lstm_bounded/4m_anneal.pt")

Training on device mps
Episode 1: Recent average episodic reward: 0.00, recent average episodic length: 1.00. Global step: 8
Episode 2: Recent average episodic reward: 0.00, recent average episodic length: 1.50. Global step: 16
Episode 3: Recent average episodic reward: 0.00, recent average episodic length: 2.67. Global step: 40
Episode 4: Recent average episodic reward: 0.01, recent average episodic length: 3.25. Global step: 56
Episode 5: Recent average episodic reward: 0.00, recent average episodic length: 2.80. Global step: 72
Episode 6: Recent average episodic reward: 0.00, recent average episodic length: 2.67. Global step: 96
Episode 7: Recent average episodic reward: 0.01, recent average episodic length: 4.14. Global step: 104
Episode 8: Recent average episodic reward: 0.01, recent average episodic length: 3.88. Global step: 120
Episode 9: Recent average episodic reward: 0.01, recent average episodic length: 3.67. Global step: 128
Episode 10: Recent average episodic reward: 0.03